FROM node:20.19.0-bullseye-slim

# Set the working directory inside the container
WORKDIR /app

# Install procps to ensure ps command is available
RUN apt-get update && apt-get install -y procps

# Copy the monorepo files into the container
COPY package.json yarn.lock ./
COPY apps ./apps
COPY tsconfig.json nest-cli.json ./

# Install dependencies for all workspaces
RUN yarn install --force

# Back to root
WORKDIR /app

# Expose ports for both microservices
EXPOSE 3000 3001

# By default, start IMDTravel service with ts-node (dev mode)
# To start AirlinesHub, override with: docker run ... -c "yarn workspace airlineshub start:dev"
CMD ["yarn", "workspace", "imdtravel", "start:dev"]