import type { Metadata } from "next";
import { AuthProvider } from './contexts/AuthContext';
import  Nav  from './components/Nav';

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import GoogleFonts from './GoogleFonts';
import ProtectedRoute from './components/ProtectedRoute';


export const metadata: Metadata = {
  title: "Quack",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
      <GoogleFonts />
       <AuthProvider>
        <Nav />
	<main>
	        {children}
	</main>
       </AuthProvider>
      </body>
    </html>
  );
};
